// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvitijfnwprzddyxdjeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2aXRpamZud3ByemRkeXhkamVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODE5MTQsImV4cCI6MjA2NDQ1NzkxNH0.TuoMgUypndtKeFSJUJuZmmleVk6AA09W6A0M9Sk1Duc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);